// Resume Data
export const RESUME_DATA_REQUEST = "RESUME_DATA_REQUEST";
export const RESUME_DATA_FAILURE = "RESUME_DATA_FAILURE";


export const POST_RESUME_DATA_SUCCESS = "POST_RESUME_DATA_SUCCESS";
export const GET_RESUME_DATA_SUCCESS = "GET_RESUME_DATA_SUCCESS";
export const PATCH_RESUME_DATA_SUCCESS = "PATCH_RESUME_DATA_SUCCESS"
export const DELETE_RESUME_DATA_SUCCESS = "DELETE_RESUME_DATA_SUCCESS"



// Authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";


// Signup
export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE = "USER_FAILURE";
export const USER_SUCCESS = "USER_SUCCESS";
